"""Regenerate the generated block of each section README (its Map of Content).

Only the text between the ``qp:moc`` markers is owned by this module; everything
around it is hand-written and preserved.
"""

from __future__ import annotations

from pathlib import Path

from .vault import Note, Section, Vault

START = "<!-- qp:moc:start (generated by `./qp index`; edit notes, not this table) -->"
END = "<!-- qp:moc:end -->"
TRACK_ABBR = {"quant-trader": "T", "quant-research": "R", "quant-dev": "D"}


def _link(section: Section, note: Note) -> str:
    rel = note.path.relative_to(Path(section.folder)).as_posix()
    return f"[{note.title}]({rel.replace(' ', '%20')})"


def public_cards(note: Note) -> int:
    """Cards defined in public notes only: private overlay cards merged into a topic must never
    leak into the committed README tables (and would make them differ between machines)."""
    return sum(1 for c in note.cards if not c.note_id.startswith("private:"))


def render(section: Section) -> str:
    topics = [n for n in section.notes if n.trackable]
    other = [n for n in section.notes if not n.trackable and not n.id.startswith("moc:")]
    lines = [START]
    if topics:
        hours = sum(n.est_hours for n in topics)
        lines += [
            "",
            f"{len(topics)} topics, about {hours:g} study hours. Tracks: T = trader, R = researcher, D = developer.",
            "",
            "| # | Topic | Tracks | Tier | Hours | Status | Cards |",
            "| ---: | :--- | :---: | :--- | ---: | :--- | ---: |",
        ]
        for n in topics:
            tracks = "".join(TRACK_ABBR.get(t, "?") for t in n.tracks)
            row = f"| {n.order:02d} | {_link(section, n)} | {tracks} | {n.tier} | {n.est_hours:g} | {n.status} | {public_cards(n)} |"
            lines.append(row)
    if other:
        lines += ["", "### Supporting material", ""]
        lines += [f"- {_link(section, n)} ({n.type})" for n in other]
    lines += ["", END]
    return "\n".join(lines)


def update_readme(vault: Vault, section: Section, apply: bool) -> bool:
    """Return True when the README changed (or would change)."""
    path = vault.root / section.folder / "README.md"
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    block = render(section)
    if START in text and END in text:
        head, _, rest = text.partition(START)
        _, _, tail = rest.partition(END)
        new = head + block + tail
    else:
        new = text.rstrip() + "\n\n" + block + "\n"
    if new == text:
        return False
    if apply:
        path.write_text(new, encoding="utf-8")
    return True


def update_all(vault: Vault, apply: bool = True) -> list[str]:
    return [s.folder for s in vault.sections if indexed(vault, s) and update_readme(vault, s, apply)]


def indexed(vault: Vault, section: Section) -> bool:
    """Libraries and READMEs with ``index: false`` (hand-curated lists) get no generated block."""
    readme = vault.notes.get(f"moc:{section.folder}")
    return not section.library and not section.private and not (readme and str(readme.meta.get("index")).lower() == "false")
